### ISSUE TITLE
In webgme 2.x.x, user display + logout buttons and icons are removed from the header panel

### ISSUE THREAD

**Issue by finger563** [dfst/webgme-breadcrumbheader#12]
Should add them back into the Panel's `initialize` function, just as they are added by the default header panel:

https://github.com/webgme/webgme/blob/master/src/client/js/Panels/Header/HeaderPanel.js#L108

**Comment by finger563** [comment]
easier to do by just adding `disableUserProfile: false` to the `defaultConfig`

**Comment by brollb** [comment]
yeah, that was accidental - I don't believe that portion was there during the initial creation of this lib. It would be nice to refactor the headerpanel in webgme so I could extend it w/o overriding the whole function

**Comment by finger563** [comment]
Agreed; I can also over-ride it in `components.json`, but then I have to use two components: `BreadcrumbHeader` and `BreadCrumbHeader` to set the `style` and the `disableUserProfile`

**Comment by brollb** [comment]
The inconsistencies have been fixed in #18

**Comment by brollb** [comment]
Is this still a problem? It should be calling the same method as in the generic header: https://github.com/dfst/webgme-breadcrumbheader/blob/master/src/visualizers/panels/BreadcrumbHeader/BreadcrumbHeaderPanel.js#L47
