### ISSUE TITLE
feature request: support for root selection through component configuration

### ISSUE THREAD

**Issue by finger563** [dfst/webgme-breadcrumbheader#9]
Similarly to how we can set the root node of the tree-browser, it would be great to set the root node of the breadcrumbheader (i.e. show all parents until parent is either null or parent is the root node)

**Comment by brollb** [comment]
what should happen if the user navigates to a node before the selected root? Should it not show anything or show the otherwise hidden path?

**Comment by finger563** [comment]
Preferably not show anything?

-----Original Message-----
